# Generated by Django 2.2.5 on 2019-09-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='meeting',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='web.Meeting'),
        ),
    ]
